apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: datadog

  sources:
    # 1) Helm chart source
    - repoURL: https://helm.datadoghq.com
      chart: datadog
      targetRevision: 3.164.1
      helm:
        valueFiles:
          - $values/clusters/dev/datadog/values.yaml

    # 2) Git source for values
    - repoURL: https://github.com/ozistephen/ozistephen-supporthub-gitops.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
