apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 61.7.2
    helm:
      valueFiles:
        - $values/environments/dev/monitoring/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  # This is the key that makes valueFiles come from your Git repo
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 61.7.2
      helm:
        valueFiles:
          - $values/environments/dev/monitoring/values.yaml
    - repoURL: https://github.com/oziomastephen/oziomastephen-supporthub-gitops.git
      targetRevision: main
      ref: values
